# Generated by Django 5.1.6 on 2025-02-12 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Категория")),
                ("picture", models.ImageField(upload_to="categories/")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "title_lower",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Строчное название",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "ingredients",
                    models.TextField(default="Не указано", verbose_name="Ингредиенты"),
                ),
                ("cooking_steps", models.TextField(verbose_name="Этапы приготовления")),
                (
                    "cooking_time",
                    models.IntegerField(verbose_name="Время приготовления (минуты)"),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="recipes/"),
                ),
                ("post_date", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=6,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipesapp.category",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
